modLoader = "javafml" #mandatory
loaderVersion = "[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"
[[mods]] #mandatory
modId = "crazycrew" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "CrazyCrew" #mandatory
authors = "YaBoiChips, CATboardBETA"
description = '''

'''
[[dependencies.crazycrew]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[39,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.crazycrew]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"
